void PosHor_loop(float _RX_s, float _RZ_s);
void PosVer_loop(float _RY_s);
void VelHor_loop(float _VRX_s, float _VRZ_s);
void VelVer_loop(float _VRY_s);
void SetVRS(void);
void Att_loop(float _GAMMA_s, float _PSI_s, float _TETA_s);
void Rate_loop(float _RateX_s, float _RateY_s, float _RateZ_s);
void ServoOut(float _AttctrlX, float _AttctrY, float _AttctrlZ);
void Acc_loop(float _AccX_s, float _AccY_s, float _AccZ_s);
void AttInitial(float ax, float ay, float az, float mx, float my, float mz);
void AttUpdate(float ax, float ay, float az, float gx, float gy, float gz, float mx, float my, float mz);
void Geo2Ine(double Lat, double Lon, float h, double Target[3], double c[3][3]);
void IMUCheck(void);
void GPS_Model(void);
void OptModel(void);
void GetMagValues(void);
void RCProcess(void);
void ControlInitial(void);
void MainProcessInt(void);
void Alt_Estimate(void);
void SetPitchRoll(void);
void SetYaw(void);
void Tcmmand2Lift(void);
void FlyModeCtrl(void);
void ActionFunction(unsigned char FlyMode);
void Brake(void);
void AttitudeMode(void);
void StableMode(void);
void HoveringMode(void);
void LaunchMode(void);
void LandingMode(void);
void ReversalMode(void);
void MissionPlanner(void);
void Limit(float *tmp, float min, float max);
float gauss(float Std, float Mean);

void UpdateHomePoint(void);
void MainProcessInt(void);
char CalMagDclnofEarth(float latitude, float longitude, float alt);
float get_lookup_table_val(unsigned lat_index, unsigned lon_index);
void AttAllign(void);
void MagMeterChk(void);
//void ChooseGPS(void);
void BaroTimeSync(void);
void MagInt(void);
void MagPreProcess(void);
void MagCalibInv(void);
void PSIFusion(void);
void GPSTimeSync(void);
void GPSPreProcess(void);
void OptTimeSync(void);
void OptPreProcess(void);
void SonarTimeSync(void);
void SonarPreProcess(void);
void Fusion(void);
void AttitudeUpdate(void);
void VelUpdate(void);
void PosUpdate(void);
void FlyControl(void);
void SonarOK(void);
void FusionSourceChoose(void);
void AeroCofsEstimate(void);
void VehicleMoving(void);
void MagCalibInit(void);
void VCorrect(float dVX, float dVZ);
void RCorrect(float dRX, float dRZ);

void StatusInit(void);
void TakeofforLanding(void);
void BeforeFly(void);
void gs_calibration_hover(short a, short b);
void MagFusionInit(short a);
void NavInit(void);

void HCorrect(void);
float *MeanCal(float *a, unsigned char b,float aa[2]);
void OptErrEst(void);
char CalMagDclnofEarth(float latitude, float longitude, float alt);
extern void CrossProduct(float *C, float *A, float *B);
void BaroFilter(void);
void IMUCorrect(void);
void EMMcSave(void);
unsigned short Float2Short(float a, float b);
void PrintEMMC(unsigned short *EMMC, short N);
void UpdateOrigin(void);
void dABYCtl(void);


extern void initial(void);
extern void Quadrotor_dynamic(void);
extern void Magnetometers_Model(void);
